version: '3.1'

services:
  db:
    image: mysql
    container_name: carros-test
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - carros_test:/var/lib/mysql

volumes:
  carros_test: